### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [skaufhold/poe-superfilter#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

**Comment by stkfd** [comment]
The dependency is currently only required due to the use of docopt.rs for the argument parsing in the CLI part of the application. This will be resolved as soon as I migrate off of docopt to clap-rs (which is bound to happen anyways) or docopt moves to Serde, whichever happens first.

**Comment by dtolnay** [comment]
Great! On docopt's end they are tracking this in https://github.com/docopt/docopt.rs/issues/128.

**Comment by stkfd** [comment]
Migration to clap is now complete, the next release will include the change.
